### PR TITLE
monolog 2 support

### PR DESCRIPTION
**Pull request by mihaileu**
* **What kind of change does this PR introduce?** 
feature

* **What is the current behavior?**
not supporting monolog

* **What is the new behavior (if this is a feature change)?**
it will support monolog 2.0
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
yes, thei will need to update application with monolog 2.0
* **Other information**:

### CODE REVIEW

**Comment by ALTELMA** [comment]
Is it possible to accept this PR? I need to use this without downgrade Monolog from 2 to 1.

**Comment by maxbanton** [comment]
Hi @mihaileu. 
Thanks for your PR.

Unfortunately, I can’t accept your PR right now, because breaking changes introduced, until I check everything, including CI/CD piplines. Also, with the transition to PHP 7.2, a new major version of the library should be released, which will also require additional efforts. In any case, a new version with support for Monolog 2 is planned soon.
cc @ALTELMA 

Kind regards,
Max.

**Comment by ALTELMA** [comment]
OK, Please let me know when you release a new version.

**Comment by maxbanton** [comment]
Hi @mihaileu @ALTELMA!
Please check new release https://github.com/maxbanton/cwh/releases/tag/v2.0.0

**Pull request closed without merging**
