### PR TITLE
Prevent empty tags as argument when creating logGroup

### PR DESCRIPTION
**Pull request by holtkamp**
As reported in https://github.com/maxbanton/cwh/issues/15

### CODE REVIEW

**Comment by maxbanton** [comment]
Hi @holtkamp!
Thank for your PR.
Build of your pull request has been failed - seems like some functionality is broken.
Please fix your code.

Thanks,
Max.

**Comment by stevethomas** [comment]
This is an important PR, the handler silently fails when empty tags are passed (as is the default). It took me quite a while to work out what the problem was! 

FWIW, I think #11 is also worthwhile, the handler failing to initialize is an exceptional circumstance.

**Comment by maxbanton** [comment]
Closed because of https://github.com/maxbanton/cwh/pull/19

**Comment by maxbanton** [comment]
Hi @stevethomas!
Issue should be fixed now with latest library version.
Please update and test it.
Thanks.

**Comment by stevethomas** [comment]
Thanks for your promptness @maxbanton, looks like the issue is resolve!

**Comment by holtkamp** [comment]
on the road now, so comment via email, is this correct? Seems weird...

" if (!empty($this->tags) > 0) {"

**Comment by stevethomas** [comment]
Not sure where you saw that? I'm seeing 
````
  if(count($this->tags) > 0){
````

**Comment by maxbanton** [comment]
Hi, @holtkamp. You are right, I made a mistake, it should be `if (!empty($this->tags)) {` instead of `if (!empty($this->tags) > 0) {`.
Fixed it.
Thank you.

**Pull request closed without merging**
